-- MySQL Script generated by MySQL Workbench
-- mié 08 nov 2017 15:28:47 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema analisis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `analisis` ;

-- -----------------------------------------------------
-- Schema analisis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analisis` DEFAULT CHARACTER SET utf8 ;
USE `analisis` ;

-- -----------------------------------------------------
-- Table `analisis`.`tipo_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analisis`.`tipo_estado` (
  `idtipo_estado` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `analisis`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analisis`.`cuenta` (
  `idcuenta` INT(3) NOT NULL AUTO_INCREMENT,
  `nombre_cuenta` VARCHAR(45) NOT NULL,
  `suma_resta` TINYINT(1) NULL,
  `tipo_estado_idtipo_estado` INT(2) NOT NULL,
  `cuenta_idcuenta` INT(3) NOT NULL,
  PRIMARY KEY (`idcuenta`),
  INDEX `fk_cuenta_tipo_estado1_idx` (`tipo_estado_idtipo_estado` ASC),
  INDEX `fk_cuenta_cuenta1_idx` (`cuenta_idcuenta` ASC),
  CONSTRAINT `fk_cuenta_tipo_estado1`
    FOREIGN KEY (`tipo_estado_idtipo_estado`)
    REFERENCES `analisis`.`tipo_estado` (`idtipo_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_cuenta1`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `analisis`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `analisis`.`tipoEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analisis`.`tipoEmpresa` (
  `idtipoEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipoEmpresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analisis`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analisis`.`empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpresa` VARCHAR(45) NOT NULL,
  `tipoEmpresa_idtipoEmpresa` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_empresa_tipoEmpresa1_idx` (`tipoEmpresa_idtipoEmpresa` ASC),
  CONSTRAINT `fk_empresa_tipoEmpresa1`
    FOREIGN KEY (`tipoEmpresa_idtipoEmpresa`)
    REFERENCES `analisis`.`tipoEmpresa` (`idtipoEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analisis`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analisis`.`registro` (
  `idregistro` INT(4) NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(10,4) NOT NULL,
  `cuenta_idcuenta` INT(3) NOT NULL,
  `empresa_idEmpresa` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`idregistro`, `cuenta_idcuenta`),
  INDEX `fk_registro_cuenta1_idx` (`cuenta_idcuenta` ASC),
  INDEX `fk_registro_empresa1_idx` (`empresa_idEmpresa` ASC),
  CONSTRAINT `fk_registro_cuenta1`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `analisis`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_empresa1`
    FOREIGN KEY (`empresa_idEmpresa`)
    REFERENCES `analisis`.`empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `analisis`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analisis`.`usuario` (
  `idusuario` INT(3) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `usuername` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
